"""
InsightPulse AI - Presentation Automation Engine v1.0
=====================================================================
Automates 'Power BI style' presentations from natural language data queries.
Generates PPTX files and structured JSON for interactive UI previews.
"""
from typing import List, Dict, Any
try:
    from pptx import Presentation
    from pptx.util import Inches, Pt
except ImportError:
    Presentation = None

def generate_presentation_json(query: str, data_result: Dict[str, Any]) -> Dict[str, Any]:
    """Creates a structured JSON representing slides for the UI."""
    slides = [
        {
            "title": "Executive Data Summary",
            "subtitle": f"Analysis requested: {query}",
            "type": "title"
        },
        {
            "title": "Core Intelligence Insights",
            "content": data_result.get("insights", ["Analyzing trends...", "Identifying anomalies..."]),
            "type": "bullets"
        }
    ]
    
    # Add charts as slide references
    for chart in data_result.get("charts", []):
        slides.append({
            "title": chart.get("title", "Visual Data Analysis"),
            "chart_type": chart.get("type"),
            "fig_json": chart.get("fig_json"),
            "type": "chart"
        })
        
    slides.append({
        "title": "Conclusion & Recommendations",
        "content": ["Strategic optimization recommended based on current data trajectory."],
        "type": "bullets"
    })
    
    return {"slides": slides}

def export_to_pptx(query: str, data_result: Dict[str, Any]) -> bytes:
    """Exports the generated intelligence into a professional PPTX file."""
    if not Presentation:
        return b""
        
    prs = Presentation()
    
    # Slide 1: Title
    slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(slide_layout)
    slide.shapes.title.text = "InsightPulse AI Intelligence Report"
    slide.placeholders[1].text = f"Query: {query}\nGenerated by J.A.R.V.I.S. Neural Core"
    
    # Slide 2: Insights
    slide_layout = prs.slide_layouts[1]
    slide = prs.slides.add_slide(slide_layout)
    slide.shapes.title.text = "Strategic Insights"
    tf = slide.placeholders[1].text_frame
    for insight in data_result.get("insights", []):
        p = tf.add_paragraph()
        p.text = insight
        p.level = 0
        
    # Save to buffer
    import io
    pptx_io = io.BytesIO()
    prs.save(pptx_io)
    return pptx_io.getvalue()
